---
- hosts: workstation

  tasks:
    - name: run .osx file
      # TODO: Use sudo once .osx can be run via root with no user interaction.
      shell: ~/Dropbox/Apps/setup/dotfiles/.osx --no-restart
      changed_when: false
      sudo: yes